/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

class MainTest
{
    @Test void appHasAGreeting()
    {
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
